<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Certificate;
use App\Services\PKI\CAManager;
use Illuminate\Http\Request;
use Exception;

class CertificateController extends Controller
{
    protected CAManager $caManager;

    public function __construct(CAManager $caManager)
    {
        $this->caManager = $caManager;
    }

    /**
     * Download the Root CA Certificate (Public)
     */
    public function downloadRootCert()
    {
        $path = base_path('pki-keys/root_ca.crt');
        if (!file_exists($path)) {
            return response()->json(['message' => 'Root CA not found. App needs to be bootstrapped by admin.'], 404);
        }

        return response()->download($path, 'root_ca.crt', [
            'Content-Type' => 'application/x-x509-ca-cert',
        ]);
    }

    /**
     * Download Certificate Revocation List (CRL) (Public)
     */
    public function downloadCrl()
    {
        $revokedSerials = Certificate::where('is_revoked', true)
            ->select('serial_number', 'revoked_at', 'revoke_reason')
            ->get();

        return response()->json([
            'crl_name' => 'TrustlessSign CRL',
            'last_update' => now()->toIso8601String(),
            'revoked_certificates' => $revokedSerials->map(fn($c) => [
                'serial_number' => $c->serial_number,
                'revoked_at' => $c->revoked_at->toIso8601String(),
                'reason' => $c->revoke_reason ?? 'Unspecified'
            ])
        ]);
    }

    /**
     * Download specific user certificate (Public)
     */
    public function downloadUserCert($serial)
    {
        $cert = Certificate::where('serial_number', $serial)->first();
        if (!$cert) {
            return response()->json(['message' => 'Certificate not found.'], 404);
        }

        return response($cert->cert_pem, 200)
            ->header('Content-Type', 'application/x-x509-ca-cert')
            ->header('Content-Disposition', 'attachment; filename="cert_' . $serial . '.crt"');
    }

    /**
     * Issue User Certificate from CSR (Authenticated Extension)
     * 
     * Multi-Device Architecture: Sertifikat baru TIDAK menggantikan sertifikat lama.
     * Setiap perangkat dapat memiliki sertifikat aktif secara bersamaan.
     */
    public function issue(Request $request)
    {
        $request->validate([
            'csr_pem'           => 'required|string',
            'device_name'       => 'nullable|string|max:128',
            'device_identifier' => 'nullable|string|max:64',
        ]);

        try {
            // [Trustless] Revoke semua cert aktif user ini — satu user, satu cert aktif
            \App\Models\Certificate::where('user_id', $request->user()->id)
                ->where('is_revoked', false)
                ->update([
                    'is_revoked'    => true,
                    'revoked_at'    => now(),
                    'revoke_reason' => 'Superseded by new certificate generated by user',
                ]);

            // Issue using PKI service
            $certData = $this->caManager->issueUserCertificate($request->user()->id, $request->csr_pem);

            $cert = Certificate::create([
                'user_id'           => $request->user()->id,
                'serial_number'     => $certData['serial_number'],
                'subject_cn'        => $certData['subject_cn'],
                'device_name'       => $request->input('device_name'),
                'device_identifier' => $request->input('device_identifier'),
                'cert_pem'          => $certData['cert_pem'],
                'expires_at'        => $certData['expires_at'],
                'is_revoked'        => false,
            ]);

            return response()->json([
                'message'     => 'Certificate issued successfully.',
                'certificate' => $cert
            ], 201);

        } catch (Exception $e) {
            return response()->json(['message' => 'Failed to issue certificate: ' . $e->getMessage()], 400);
        }
    }

    /**
     * Get ALL active certificates of currently logged-in user (Authenticated Extension)
     * Returns an array — supports multi-device architecture.
     */
    public function myCertificate(Request $request)
    {
        $certs = Certificate::where('user_id', $request->user()->id)
            ->where('is_revoked', false)
            ->where('expires_at', '>', now())
            ->orderBy('issued_at', 'desc')
            ->get();

        if ($certs->isEmpty()) {
            return response()->json([
                'message'         => 'No active certificate found.',
                'has_certificate' => false,
                'certificates'    => []
            ], 200);
        }

        return response()->json([
            'has_certificate' => true,
            'certificates'    => $certs,
        ], 200);
    }

    /**
     * Bootstrap Root CA (Admin Only)
     */
    public function bootstrapCA(Request $request)
    {
        if (!$request->user() || !$request->user()->is_admin) {
            return response()->json(['message' => 'Forbidden. Admin privilege required.'], 403);
        }

        $request->validate([
            'common_name'  => 'nullable|string|max:255',
            'country'      => 'nullable|string|size:2',
            'organization' => 'nullable|string|max:255',
        ]);

        try {
            $commonName   = $request->input('common_name', 'TrustlessSign Root CA');
            $country      = $request->input('country', 'ID');
            $organization = $request->input('organization', 'TrustlessSign');

            $result = $this->caManager->bootstrapCA($commonName, $country, $organization);

            return response()->json([
                'message'          => 'Root CA bootstrapped successfully.',
                'root_certificate' => $result['cert']
            ]);
        } catch (Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Revoke a specific certificate by serial number (User Self-Service)
     * Pengguna hanya bisa mencabut sertifikat milik dirinya sendiri.
     */
    public function revokeOwn(Request $request, $serial)
    {
        $request->validate([
            'reason' => 'nullable|string|max:255',
        ]);

        $cert = Certificate::where('serial_number', $serial)
            ->where('user_id', $request->user()->id) // Pastikan milik user sendiri
            ->first();

        if (!$cert) {
            return response()->json(['message' => 'Certificate not found or not owned by you.'], 404);
        }

        if ($cert->is_revoked) {
            return response()->json(['message' => 'Certificate is already revoked.'], 400);
        }

        $cert->update([
            'is_revoked'    => true,
            'revoked_at'    => now(),
            'revoke_reason' => $request->input('reason', 'Revoked by user'),
        ]);

        return response()->json([
            'message'     => 'Certificate revoked successfully.',
            'certificate' => $cert
        ]);
    }

    /**
     * Revoke any certificate by serial number (Admin Only)
     */
    public function revoke(Request $request, $serial)
    {
        if (!$request->user() || !$request->user()->is_admin) {
            return response()->json(['message' => 'Forbidden. Admin privilege required.'], 403);
        }

        $request->validate([
            'reason' => 'nullable|string|max:255',
        ]);

        $cert = Certificate::where('serial_number', $serial)->first();
        if (!$cert) {
            return response()->json(['message' => 'Certificate not found.'], 404);
        }

        if ($cert->is_revoked) {
            return response()->json(['message' => 'Certificate is already revoked.'], 400);
        }

        $cert->update([
            'is_revoked'    => true,
            'revoked_at'    => now(),
            'revoke_reason' => $request->input('reason', 'Revoked by admin'),
        ]);

        return response()->json([
            'message'     => 'Certificate revoked successfully.',
            'certificate' => $cert
        ]);
    }
}
