services:
  app:
    build: ./web
    container_name: trustlesssign-app
    environment:
      - DB_HOST=shared-db
    networks:
      - shared-network
    volumes:
      - ./web:/var/www/html
      - ./pki-keys:/var/www/html/pki-keys
      - ./secrets:/var/www/html/secrets
      - ./chrome-extension:/var/www/chrome-extension:ro
    restart: unless-stopped

networks:
  shared-network:
    external: true
    name: shared-network
